"""Repository boundary for persisted Resume artifacts and attempts."""

from typing import Protocol

from src.get_me_in.domain.artifacts import Artifact, ArtifactBuildAttempt, ArtifactOperation


class ArtifactRepository(Protocol):
    def get_operation(self, operation_key: str) -> ArtifactOperation | None: ...
    def save_operation(self, operation: ArtifactOperation) -> None: ...
    def next_version(self, path: str) -> int: ...
    def list_artifacts(self, path: str | None = None) -> tuple[Artifact, ...]: ...
    def list_build_attempts(self, source_path: str | None = None) -> tuple[ArtifactBuildAttempt, ...]: ...
    def close(self) -> None: ...
